local_costmap:
  global_frame: /summit_xl_odom
  robot_base_frame: /summit_xl_base_footprint
  update_frequency: 5.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.02 #0.05
  transform_tolerance: 0.5
  footprint_padding: 0.0 # helps with passing through narrow passages
  always_send_full_costmap: true
  static_layer:
    enabled: false

# execute `rospack plugins --attrib=plugin costmap_2d` to look at all available costmap plugins
  plugins:
    - {name: obstacle_3d_layer,   type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
    - {name: obstacle_2d_layer,   type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
