joint_blw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: rear_left_wheel_joint
joint_brw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: rear_right_wheel_joint
joint_frw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_right_wheel_joint
joint_flw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_left_wheel_joint
  
robotnik_base_control:
  type: summit_xl_controller/SummitXLController
  joint:
    front_right_wheel_joint:
      name: front_right_wheel_joint
      max_speed: 27.27 # rad/s
    front_left_wheel_joint:
      name: front_left_wheel_joint
      max_speed: 27.27 # rad/s
    rear_right_wheel_joint:
      name: rear_right_wheel_joint
      max_speed: 27.27 # rad/s
    rear_left_wheel_joint:
      name: rear_left_wheel_joint
      max_speed: 27.27 # rad/s
  linear_speed_limit: 1.5 # m/s
  linear_acceleration_limit: 3 # m/s^2
  angular_speed_limit: 3 # rad/s
  angular_acceleration_limit: 3 # rad/s^2
  odom_frame: odom
  robot_base_frame: base_footprint
  odom_broadcast_tf: true
  odom_topic: 'robotnik_base_control/odom'
  wheel_base: 0.445
  track_width: 0.415
  wheel_diameter: 0.220
  cmd_watchdog_duration: 0.2
  imu_watchdog_duration: 0.1
  imu_topic: imu/data
  odom_publish_frequency: 100
  cmd_vel        : 'robotnik_base_control/cmd_vel'
  kinematic_mode : 'skid'
  motion_odometry: true
  in_motion_timer: 2.0

joint_read_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 100.0



