base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
  odom_topic: odom
  map_frame: map

  # Trajectory

  teb_autosize: True
  dt_ref: 0.3 # Desired temporal resolution of the trajectory
  dt_hysteresis: 0.05 # Hysteresis for automatic resizing depending on the current temporal resolution, usually approx. 10% of dt_ref is recommended
  min_samples: 3 # Minimum number of samples (should be always greater than 2)
  global_plan_overwrite_orientation: True # overwrite orientation_mode param in global planner
  global_plan_viapoint_sep: 0.5 # negative, do not use viapoints. positive, use them. the actual value does not matter
  max_global_plan_lookahead_dist: 4.0 # maximum length of the subset of the global plan taken into account for optimization
  force_reinit_new_goal_dist: 1.0
  feasibility_check_no_poses: 3
  publish_feedback: false
  shrink_horizon_backup: true
  allow_init_with_backwards_motion: true
  exact_arc_length: false
  shrink_horizon_min_duration: 10

  # Robot

  max_vel_x: 0.15
  max_vel_x_backwards: 0.10
  max_vel_theta: 0.2
  max_vel_y: 0.1 # omni drive
  acc_lim_y: 0.2 # omni drive
  acc_lim_x: 0.1
  acc_lim_theta: 0.2
  min_turning_radius: 0.0
  wheelbase: 0.0 # not used, is omni
  cmd_angle_instead_rotvel: false # not used, is omni
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    #type: "circular"
    #radius: 0.5 # for type "circular"
    type: "line"
    line_start: [-0.16, 0.0] # for type "line"
    line_end: [0.16, 0.0] # for type "line"
    #front_offset: 0.2 # for type "two_circles"
    #front_radius: 0.2 # for type "two_circles"
    #rear_offset: 0.2 # for type "two_circles"
    #rear_radius: 0.2 # for type "two_circles"
    #vertices: [ [0.40, -0.31], [0.40, 0.31], [-0.40, 0.31], [-0.40, -0.31] ] # for type "polygon"

  # GoalTolerance

  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 1
  free_goal_vel: False

  # Obstacles

  min_obstacle_dist: 0.33 # minimum distance to obstacle: it depends on the footprint_model
  include_costmap_obstacles: True # use the local costmap
  costmap_obstacles_behind_robot_dist: 1.0 # distance at which obstacles behind the robot are taken into account
  obstacle_poses_affected: 30 # unused if legacy_obstacle_association is false
  inflation_dist: 0.37 # greater than min_obstacle_dist to take effect
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 1.5 # the obstacles that will be taken into account are those closer than min_obstacle_dist*factor, if legacy is false
  obstacle_association_cutoff_factor: 5.0 # the obstacles that are further than min_obstacle_dist * factor will not be taken into account, if legacy is false
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  #costmap_converter_plugin: "" # deactivate plugin
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  # costmap_converter/CostmapToLinesDBSRANSAC:
  #    cluster_max_distance: 0.4

  # Optimization

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True # optimize
  optimization_verbose: False
  penalty_epsilon: 0.09 # small safefy margin to penalty functions for hard-constraint approximations
  weight_max_vel_x: 1
  weight_max_vel_y: 1
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_y: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 5000 # prefer nonholonomic driving
  weight_kinematics_forward_drive: 300 # prefer forward driving
  weight_kinematics_turning_radius: 1 # prefer turns that respect the min_turning_radius, not used if differential (min_turning_radius = 0)
  weight_optimaltime: 1 # prefer trajectories with less transition time
  weight_obstacle: 100 # prefer trajectories that respect the min_obstacle_dist
  weight_inflation: 5 # prefer trajectories that respect the inflation of the obstacles
  #weight_dynamic_obstacle: 10 # not in use yet
  weight_viapoint: 30 # prefer trajectories that respect the viapoints in the global path
  weight_adapt_factor: 2 # factor to multiply some weights (currently only weight_obstacle) at each iteration (gives better results than a huge value for the weight)

  # Homotopy Class Planner

  enable_homotopy_class_planning: False # currently not used
  simple_exploration: False
  enable_multithreading: True
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 4.0
  selection_viapoint_cost_scale: 1.0
  selection_alternative_time_cost: False
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 6
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  obstacle_keypoint_offset: 0.1
  visualize_hc_graph: False
  oscillation_recovery: True
