sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /summit_xl/arm_camera/depth_registered/points_throttled #should be depth_registered on the summit_xl robot
    max_range: 1.2
    point_subsample: 1
    padding_offset: 0.05
    padding_scale: 2.0
    max_update_rate: 0.5
